FROM node:22-alpine3.20

RUN addgroup -S frontend
RUN adduser -S frontend -G frontend

WORKDIR /app
# COPY . . 
RUN chown -R frontend:frontend /app

USER frontend
RUN echo >> "Hello"

# Purpose: Informs Docker that the container listens on port 3000 for network traffic.
# Why: While it doesn’t actually open the port, it’s a helpful hint for anyone running or linking to this container. The application likely listens on port 3000.
EXPOSE 3000

CMD ["sh", "-c", "npm run build && npm run start"]
