services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: task-1-frontend
    volumes:
      - ./frontend:/app:rw
    networks:
      - frontend_network
  
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: task-1-backend
    volumes:
      - ./backend:/app:rw
    depends_on:
      - database
    networks:
      - backend_network

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: task-1-nginx
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl 
    ports:
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - backend_network
      - frontend_network

  database:
    image: mongo:6.0
    container_name: task-1-mongodb
    volumes:
      - mongo_data:/data/db
    networks:
      - backend_network

# we have to add this for named volumes,not for bind mount
volumes:
  mongo_data:
    driver: local

networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge