services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: task-1-frontend
    volumes:
      - ./frontend:/app:rw
    ports:
      - "3000:3000"
  
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: task-1-backend
    volumes:
      - ./backend:/app:rw
    ports:
      - "4000:4000"
    depends_on:
      - database

  database:
    image: mongo:6.0
    container_name: task-1-mongodb
    volumes:
      - ./mongo_data:/data/db
    ports:
      - "27017:27017"

# we have to add this for named volumes,not for bind mount
volumes:
  mongo_data:
    driver: local