# Use the Nginx base image
FROM nginx:latest

# Install dependencies for OpenSSL
RUN apt-get update && apt-get install -y \
    openssl \
    curl \
    && apt-get clean

# Create directory for SSL certificates
RUN mkdir -p /etc/nginx/ssl

COPY ./entrypoint.sh /etc/nginx/entrypoint.sh
RUN chmod +x /etc/nginx/entrypoint.sh

# Expose HTTPS port only
EXPOSE 443

# Set entrypoint
CMD ["bash", "/etc/nginx/entrypoint.sh"]
